hunav_loader:
  ros__parameters:
    map: cafe
    publish_people: true
    agents:
      - agent1
    agent1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 4
        configuration: 0
        duration: 40.0
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 3.484565
        y: 6.934117
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 3.378858
        y: -4.586833
        h: 1.250000
