advisors:
  Greedy:
    description: Advisor-favors-steps-that-will-get-robot-closer-to-target
    active: true
    weight: [1, 0, 0, 0, 0]
  GreedyRotation:
    description: Advisor-favors-steps-that-will-get-robot-closer-to-target
    active: true
    weight: [1, 0, 0, 0, 0]
  ElbowRoom:
    description: Advisor-that-does-not-like-robot-to-be-too-close-to-wall
    active: true
    weight: [1, 10, -4, -0.22, 0]
  ElbowRoomRotation:
    description: Advisor-that-does-not-like-robot-to-be-too-close-to-wall
    active: true
    weight: [1, 10, -4, -0.22, 0]
  BigStep:
    description: Advisor-that-favors-making-biggest-possible-steps
    active: true
    weight: [1, 0, 0, 0, 0]
  BigStepRotation:
    description: Advisor-that-favors-making-biggest-possible-steps
    active: true
    weight: [1, 0, 0, 0, 0]
  Explorer:
    description: Advisor-that-favors-places-that-have-not-been-visited
    active: true
    weight: [1, 0.05, 0, 0, 0]
  ExplorerRotation:
    description: Advisor-that-favors-places-that-have-not-been-visited
    active: true
    weight: [1, 1.25, 0, 0, 0]
  GoAroundRotation:
    description: Advisor-that-wants-to-turn-if-robot-has-obstacle-in-front
    active: true
    weight: [1, 0, 0, 0, 0]
  ExplorerEndPoints:
    description: Advisor-that-favors-places-that-have-not-been-sensed
    active: false
    weight: [1, 0.05, 0, 0, 0]
  ExplorerEndPointsRotation:
    description: Advisor-that-favors-places-that-have-not-been-sensed
    active: false
    weight: [1, 1.25, 0, 0, 0]
  BaseLine:
    description: Advisor-that-gives-random-comments
    active: false
    weight: [1, 0, 0, 0, 0]
  BaseLineRotation:
    description: Advisor-that-gives-random-comments
    active: false
    weight: [1, 0, 0, 0, 0]
  RegionLeaverLinear:
    description: Advisor-that-leaves-a-region-without-the-target
    active: true
    weight: [1, 0, 0, 0, 0]
  RegionLeaverRotation:
    description: Advisor-that-leaves-a-region-without-the-target
    active: true
    weight: [1, 0, 0, 0, 0]
  UnlikelyField:
    description: Advisor-that-prefers-moves-in-general-direction-of-target
    active: true
    weight: [1, 0, 0, 0, 0]
  UnlikelyFieldRotation:
    description: Advisor-that-prefers-moves-in-general-direction-of-target
    active: true
    weight: [1, 0, 0, 0, 0]
  EnterLinear:
    description: Advisor-that-votes-to-go-into-a-region-which-has-target
    active: true
    weight: [1, 0, 0, 0, 0]
  EnterRotation:
    description: Advisor-that-votes-to-go-into-a-region-which-has-target
    active: true
    weight: [1, 0, 0, 0, 0]
  ConveyLinear:
    description: Advisor-that-follows-conveyors-generated-from-paths
    active: true
    weight: [1, 0, 0, 0, 0]
  ConveyRotation:
    description: Advisor-that-follows-conveyors-generated-from-paths
    active: true
    weight: [1, 0, 0, 0, 0]
  TrailerLinear:
    description: Advisor-that-follows-previous-paths
    active: true
    weight: [1, 0, 0, 0, 0]
  TrailerRotation:
    description: Advisor-that-follows-previous-paths
    active: true
    weight: [1, 0, 0, 0, 0]
  LeastAngle:
    description: Advisor-that-leaves-a-region-toward-the-target
    active: true
    weight: [1, 0, 0, 0, 0]
  LeastAngleRotation:
    description: Advisor-that-leaves-a-region-toward-the-target
    active: true
    weight: [1, 0, 0, 0, 0]
  Interpersonal:
    description: Advisor-that-does-not-violate-pedestrian-space
    active: false
    weight: [1, 0, 0, 0, 0]
  InterpersonalRotation:
    description: Advisor-that-does-not-violate-pedestrian-space
    active: false
    weight: [1, 0, 0, 0, 0]
  Front:
    description: Advisor-that-does-not-directly-confront-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  FrontRotation:
    description: Advisor-that-does-not-directly-confront-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  Rear:
    description: Advisor-that-maintains-distance-behind-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  RearRotation:
    description: Advisor-that-maintains-distance-behind-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  Side:
    description: Advisor-that-does-not-cross-perpendicularly-in-front-of-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  SideRotation:
    description: Advisor-that-does-not-cross-perpendicularly-in-front-of-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  Visible:
    description: Advisor-that-stays-in-sight-of-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  VisibleRotation:
    description: Advisor-that-stays-in-sight-of-pedestrians
    active: false
    weight: [1, 0, 0, 0, 0]
  CrowdAvoid:
    description: Advisor-that-avoids-crowded-areas
    active: false
    weight: [1, 0, 0, 0, 0]
  CrowdAvoidRotation:
    description: Advisor-that-avoids-crowded-areas
    active: false
    weight: [1, 0, 0, 0, 0]
  FindTheCrowd:
    description: Advisor-that-goes-toward-areas-with-crowd-uncertainty
    active: false
    weight: [1, 0, 0, 0, 0]
  FindTheCrowdRotation:
    description: Advisor-that-goes-toward-areas-with-crowd-uncertainty
    active: false
    weight: [1, 0, 0, 0, 0]
  RiskAvoid:
    description: Advisor-that-avoids-risky-areas
    active: false
    weight: [1, 0, 0, 0, 0]
  RiskAvoidRotation:
    description: Advisor-avoids-risky-areas
    active: false
    weight: [1, 0, 0, 0, 0]
  FindTheRisk:
    description: Advisor-that-goes-toward-areas-with-risk-uncertainty
    active: false
    weight: [1, 0, 0, 0, 0]
  FindTheRiskRotation:
    description: Advisor-goes-toward-areas-with-risk-uncertainty
    active: false
    weight: [1, 0, 0, 0, 0]
  FlowAvoid:
    description: Advisor-that-avoids-moving-against-the-flow
    active: false
    weight: [1, 0, 0, 0, 0]
  FlowAvoidRotation:
    description: Advisor-avoids-moving-against-the-flow
    active: false
    weight: [1, 0, 0, 0, 0]
  FindTheFlow:
    description: Advisor-that-goes-toward-areas-with-risk-uncertainty
    active: false
    weight: [1, 0, 0, 0, 0]
  FindTheFlowRotation:
    description: Advisor-goes-toward-areas-with-risk-uncertainty
    active: false
    weight: [1, 0, 0, 0, 0]
  Follow:
    description: Advisor-that-uses-hallway-to-approach-target
    active: false
    weight: [1, 0, 0, 0, 0]
  FollowRotation:
    description: Advisor-that-uses-hallway-to-approach-target
    active: false
    weight: [1, 0, 0, 0, 0]
  Crossroads:
    description: Advisor-that-goes-toward-highly-connected-hallway
    active: false
    weight: [1, 0, 0, 0, 0]
  CrossroadsRotation:
    description: Advisor-that-goes-toward-highly-connected-hallway
    active: false
    weight: [1, 0, 0, 0, 0]
  Stay:
    description: Advisor-that-stays-within-hallway
    active: false
    weight: [1, 0, 0, 0, 0]
  StayRotation:
    description: Advisor-that-stays-within-hallway
    active: false
    weight: [1, 0, 0, 0, 0]
